DELETE
FROM "EXPENDITURES"
WHERE "EXPENDITURE_ID" IS NULL
   OR "HOUSEHOLD_ID" IS NULL
   OR "YEAR" IS NULL
   OR "MONTH" IS NULL
   OR "PRODUCT_CODE" IS NULL
   OR "COST" IS NULL
   OR "GIFT" IS NULL;
UPDATE "EXPENDITURES"
SET "YEAR"  = "YEAR" + 1,
    "MONTH" = "MONTH" + 1,
    "COST"  = "COST" + 1,
    "GIFT"  = "GIFT" + 1;
DELETE
FROM "HOUSEHOLDS"
WHERE "HOUSEHOLD_ID" IS NULL
   OR "YEAR" IS NULL
   OR "INCOME_RANK" IS NULL
   OR "INCOME_RANK_1" IS NULL
   OR "INCOME_RANK_2" IS NULL
   OR "INCOME_RANK_3" IS NULL
   OR "INCOME_RANK_4" IS NULL
   OR "INCOME_RANK_5" IS NULL
   OR "INCOME_RANK_MEAN" IS NULL
   OR "AGE_REF" IS NULL;
UPDATE "HOUSEHOLDS"
SET "YEAR"             = "YEAR" + 1,
    "INCOME_RANK"      = "INCOME_RANK" + 1,
    "INCOME_RANK_1"    = "INCOME_RANK_1" + 1,
    "INCOME_RANK_2"    = "INCOME_RANK_2" + 1,
    "INCOME_RANK_3"    = "INCOME_RANK_3" + 1,
    "INCOME_RANK_4"    = "INCOME_RANK_4" + 1,
    "INCOME_RANK_5"    = "INCOME_RANK_5" + 1,
    "INCOME_RANK_MEAN" = "INCOME_RANK_MEAN" + 1,
    "AGE_REF"          = "AGE_REF" + 1;
DELETE
FROM "HOUSEHOLD_MEMBERS"
WHERE "HOUSEHOLD_ID" IS NULL
   OR "YEAR" IS NULL
   OR "MARITAL" IS NULL
   OR "SEX" IS NULL
   OR "AGE" IS NULL;
UPDATE "HOUSEHOLD_MEMBERS"
SET "YEAR" = "YEAR" + 1,
    "AGE"  = "AGE" + 1;
